version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting static analysis..."
  build:
    commands:
      - aws lambda invoke --function-name Staticcode-analysis-function output.json
  post_build:
    commands:
      - echo "Build complete."
