version: 0.2
phases:
  pre_build:
    commands:
      - echo "Preparing for test stack deployment..."
      - ls -R    # Debug: List all files and folders
      - pwd      # Debug: Print the current directory
      - cd securitycheckCICD  # Move into the correct folder
      - aws cloudformation validate-template --template-body file://securitygroup.yml
  build:
    commands:
      - echo "Deploying test stack..."
      - cd securitycheckCICD  # Ensure we are in the right folder
      - aws cloudformation deploy --template-file securitygroup.yml --stack-name TestStack --capabilities CAPABILITY_NAMED_IAM
  post_build:
    commands:
      - echo "Test stack deployed successfully."
