version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fixing non-breaking spaces in lambda_function.py..."
      - sed -i 's/\xC2\xA0/ /g' lambda_function.py
      - echo "Preparing for test stack deployment..."
      - aws cloudformation validate-template --template-body file://securitygroup.yml

  build:
    commands:
      - echo "Deploying test stack..."
      - aws cloudformation deploy --template-file securitygroup.yml --stack-name TestStack --capabilities CAPABILITY_NAMED_IAM

  post_build:
    commands:
      - echo "Invoking StackValidation Lambda..."
      - |
        aws lambda invoke \
          --function-name Stack-Validation-function \
          --payload '{"StackName": "TestStack"}' \
          --cli-binary-format raw-in-base64-out \
          output.json
      - cat output.json
      - |
        STATUS=$(jq -r '.status' output.json)
        if [[ "$STATUS" == "FAILED" ]]; then 
          echo "Security violations found!"
          exit 1
        fi
      - echo "Test stack validation passed."
