version: 0.2
phases:
  build:
    commands:
      - echo "Invoking StackValidation Lambda..."
      - aws lambda invoke --function-name Stack-Validation-function --payload '{\"StackName\": \"TestStack\"}' --cli-binary-format raw-in-base64-out output.json
      - cat output.json
