version: 0.2

phases:
  pre_build:
    commands:
      - echo "Preparing for test stack deployment..."
      - aws cloudformation validate-template --template-body file://securitygroup.yml

  build:
    commands:
      - echo "Deploying test stack..."
      - aws cloudformation deploy --template-file securitygroup.yml --stack-name TestStack --capabilities CAPABILITY_NAMED_IAM

  post_build:
    commands:
      - echo "Invoking StackValidation Lambda..."
      - |
          aws lambda invoke \
            --function-name Stack-Validation-function \
            --payload '{"StackName": "TestStack"}' \
            --cli-binary-format raw-in-base64-out \
            output.json
      - cat output.json
      - |
          STATUS_CODE=$(jq -r '.statusCode' output.json)
          if [[ "$STATUS_CODE" -ne 200 ]]; then 
            echo "❌ Security violations found!"
            cat output.json  # Show details of violations
            exit 1
          fi
