AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for a security group

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: CustomsecuritycheckSG-01  # ✅ Add a name here
      GroupDescription: Allow SSH and HTTP
      VpcId: vpc-0b9de864f8d26236d # Replace with your VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
