AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Test environment security group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 67.158.52.77
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 67.158.52.77
